# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapper.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmapper.proto\"\x17\n\tIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"#\n\x0epointsResponse\x12\x11\n\tpartition\x18\x01 \x01(\t2>\n\rMapperService\x12-\n\x0eSendPartitions\x12\n.IdRequest\x1a\x0f.pointsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IDREQUEST']._serialized_start=16
  _globals['_IDREQUEST']._serialized_end=39
  _globals['_POINTSRESPONSE']._serialized_start=41
  _globals['_POINTSRESPONSE']._serialized_end=76
  _globals['_MAPPERSERVICE']._serialized_start=78
  _globals['_MAPPERSERVICE']._serialized_end=140
# @@protoc_insertion_point(module_scope)
