# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmaster.proto\"5\n\rreduce_update\x12\x18\n\x10updated_centroid\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\"\"\n\x0fmessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x10\n\x02id\x12\n\n\x02id\x18\x01 \x01(\x05\"+\n\x06points\x12\x0e\n\x06points\x18\x01 \x03(\x05\x12\x11\n\tcentroids\x18\x02 \x01(\t\"!\n\x0emapperResponse\x12\x0f\n\x07mappers\x18\x01 \x01(\x05\x32\x97\x01\n\rMasterService\x12\"\n\x12PassPointsToMapper\x12\x03.id\x1a\x07.points\x12-\n\x15PassMappersToReducers\x12\x03.id\x1a\x0f.mapperResponse\x12\x33\n\x0fRecieveCentroid\x12\x0e.reduce_update\x1a\x10.messageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REDUCE_UPDATE']._serialized_start=16
  _globals['_REDUCE_UPDATE']._serialized_end=69
  _globals['_MESSAGERESPONSE']._serialized_start=71
  _globals['_MESSAGERESPONSE']._serialized_end=105
  _globals['_ID']._serialized_start=107
  _globals['_ID']._serialized_end=123
  _globals['_POINTS']._serialized_start=125
  _globals['_POINTS']._serialized_end=168
  _globals['_MAPPERRESPONSE']._serialized_start=170
  _globals['_MAPPERRESPONSE']._serialized_end=203
  _globals['_MASTERSERVICE']._serialized_start=206
  _globals['_MASTERSERVICE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
